 media:
    - name: media
      input: media111

  content:
    - name: posts
      label: Posts
      path: _posts
      type: collection
      fields:
        - name: title
          type: string
        - name: body
          type: rich-text